Repository ruby/rdoc, pull requests merged in 2022-02, with the labels that each got.

#866 Support all struct definition functions
  lib/rdoc/parser/c.rb
  test/rdoc/test_rdoc_parser_c.rb
Labels: Bug

#868 Allow cross references to logical operator methods
  lib/rdoc/cross_reference.rb
  test/rdoc/test_rdoc_cross_reference.rb
Labels: Bug

#851 Simplify attribute exclusiveness conditions
  lib/rdoc/markup/attribute_manager.rb
  lib/rdoc/parser/c.rb
  test/rdoc/test_rdoc_parser_ruby.rb
Labels: Performance

#821 Relative loading for easier development
  Rakefile
  bin/console
  exe/rdoc
  lib/rdoc.rb
  lib/rdoc/code_objects.rb
  lib/rdoc/context.rb
  lib/rdoc/generator.rb
  lib/rdoc/i18n.rb
  lib/rdoc/markdown.kpeg
  lib/rdoc/markup.rb
  lib/rdoc/parser.rb
  lib/rdoc/rd.rb
  lib/rdoc/rdoc.rb
  lib/rdoc/ri.rb
  lib/rdoc/ri/driver.rb
  lib/rdoc/rubygems_hook.rb
  lib/rdoc/servlet.rb
  lib/rdoc/stats.rb
  lib/rdoc/task.rb
  lib/rdoc/version.rb
  test/rdoc/helper.rb
  test/rdoc/support/test_case.rb
  test/rdoc/test_rdoc_alias.rb
  test/rdoc/test_rdoc_any_method.rb
  test/rdoc/test_rdoc_class_module.rb
  test/rdoc/test_rdoc_code_object.rb
  test/rdoc/test_rdoc_constant.rb
  test/rdoc/test_rdoc_context.rb
  test/rdoc/test_rdoc_cross_reference.rb
  test/rdoc/test_rdoc_extend.rb
  test/rdoc/test_rdoc_include.rb
  test/rdoc/test_rdoc_markdown.rb
  test/rdoc/test_rdoc_markdown_test.rb
  test/rdoc/test_rdoc_markup_to_html_crossref.rb
  test/rdoc/test_rdoc_method_attr.rb
  test/rdoc/test_rdoc_normal_class.rb
  test/rdoc/test_rdoc_normal_module.rb
  test/rdoc/test_rdoc_require.rb
  test/rdoc/test_rdoc_ri_driver.rb
  test/rdoc/test_rdoc_rubygems_hook.rb
  test/rdoc/test_rdoc_store.rb
  test/rdoc/test_rdoc_task.rb
  test/rdoc/test_rdoc_top_level.rb
Labels: Feature Request

#839 Make `.rdoc_options` file plain ruby objects only
  lib/rdoc/options.rb
  lib/rdoc/rdoc.rb
  test/rdoc/test_rdoc_options.rb
  test/rdoc/test_rdoc_rdoc.rb
Labels: Bug
