Repository ruby/rdoc, pull requests merged in 2024-10, with the labels that each got.

#1184 Fix ToRdoc#accept_table
  lib/rdoc/markup/to_rdoc.rb
  test/rdoc/support/text_formatter_test_case.rb
  test/rdoc/test_rdoc_markup_to_ansi.rb
  test/rdoc/test_rdoc_markup_to_bs.rb
  test/rdoc/test_rdoc_markup_to_markdown.rb
  test/rdoc/test_rdoc_markup_to_rdoc.rb
Labels: bug

#1185 Improve RDoc pages heading levels order
  ExampleMarkdown.md
  ExampleRDoc.rdoc
  History.rdoc
  LICENSE.rdoc
  TODO.rdoc
Labels: documentation

#1176 Improve method source toggling
  lib/rdoc/generator/template/darkfish/class.rhtml
  lib/rdoc/generator/template/darkfish/css/rdoc.css
  lib/rdoc/generator/template/darkfish/js/darkfish.js
Labels: enhancement

#1091 Add support for meta tags
  lib/rdoc/generator/darkfish.rb
  lib/rdoc/generator/template/darkfish/_head.rhtml
  test/rdoc/test_rdoc_generator_darkfish.rb
Labels: enhancement

#1174 Add scroll-margin-top on all :target elements
  lib/rdoc/generator/template/darkfish/css/rdoc.css
Labels: enhancement

#1190 Use scroll-margin-top on anchor targets
  lib/rdoc/generator/template/darkfish/class.rhtml
  lib/rdoc/generator/template/darkfish/css/rdoc.css
Labels: enhancement

#842 feature: Render mixed-in methods and constants with `--embed-mixins`
  lib/rdoc/code_object.rb
  lib/rdoc/code_object/class_module.rb
  lib/rdoc/generator/template/darkfish/class.rhtml
  lib/rdoc/generator/template/darkfish/css/rdoc.css
  lib/rdoc/options.rb
  test/rdoc/test_rdoc_class_module.rb
  test/rdoc/test_rdoc_options.rb
Labels: enhancement

#1191 Red-based darkfish color scheme
  lib/rdoc/generator/template/darkfish/css/rdoc.css
Labels: enhancement

#1198 Mention community-maintained themes
  README.rdoc
Labels: documentation
