Repository ruby/rdoc, pull requests merged in 2024-09, with the labels that each got.

#1169 [DOC] Fix links
  doc/rdoc/markup_reference.rb
  lib/rdoc.rb
Labels: documentation

#1175 Use pointer cursor for navigation toggle
  lib/rdoc/generator/template/darkfish/css/rdoc.css
Labels: enhancement

#1165 Add home page link to output message
  lib/rdoc/rdoc.rb
Labels: enhancement

#1181 Only let browser search through source code until it's expanded
  lib/rdoc/generator/template/darkfish/css/rdoc.css
Labels: bug
