Repository ruby/rdoc, pull requests merged in 2024-08, with the labels that each got.

#1025 Add support for mobile screen sizes on Darkfish
  lib/rdoc/generator/template/darkfish/_head.rhtml
  lib/rdoc/generator/template/darkfish/_sidebar_toggle.rhtml
  lib/rdoc/generator/template/darkfish/class.rhtml
  lib/rdoc/generator/template/darkfish/css/rdoc.css
  lib/rdoc/generator/template/darkfish/index.rhtml
  lib/rdoc/generator/template/darkfish/js/darkfish.js
  lib/rdoc/generator/template/darkfish/page.rhtml
  lib/rdoc/generator/template/darkfish/servlet_not_found.rhtml
  lib/rdoc/generator/template/darkfish/servlet_root.rhtml
  lib/rdoc/generator/template/darkfish/table_of_contents.rhtml
Labels: enhancement

#1148 Fix darkfish responsiveness issue on screens between 1024px and ~1650px
  lib/rdoc/generator/template/darkfish/css/rdoc.css
Labels: generator

#1153 [doc] Mention `.document` file in README
  README.rdoc
Labels: documentation

#1157 Modernize RDoc Darkfish template CSS
  lib/rdoc/generator/template/darkfish/_sidebar_toggle.rhtml
  lib/rdoc/generator/template/darkfish/css/rdoc.css
Labels: enhancement

#1160 Make summary triangle appear in correct place when summary text overflows to next line
  lib/rdoc/generator/template/darkfish/css/rdoc.css
Labels: bug

#1162 Make darkfish more responsive and readable on mobile devices
  lib/rdoc/generator/template/darkfish/css/rdoc.css
Labels: bug
