Repository ruby/rdoc, pull requests merged in 2024-12, with the labels that each got.

#1222 `ClassModule#superclass=` accepts a `ClassModule` as an argument
  lib/rdoc/code_object/class_module.rb
  test/rdoc/test_rdoc_class_module.rb
Labels: bug

#1218 Deprecate `main` and `title` directives
  doc/rdoc/markup_reference.rb
  lib/rdoc.rb
  lib/rdoc/markup/pre_process.rb
  lib/rdoc/parser/c.rb
  lib/rdoc/rdoc.rb
  test/rdoc/test_rdoc_markup_pre_process.rb
Labels: enhancement

#1209 Use distinct styles for note lists and label lists
  lib/rdoc/generator/template/darkfish/css/rdoc.css
  lib/rdoc/markup/to_html.rb
  test/rdoc/test_rdoc_markup_to_html.rb
Labels: bug

#1141 Expand rdoc-ref targets at the end of ri output
  lib/rdoc/ri/driver.rb
  test/rdoc/test_rdoc_ri_driver.rb
Labels: enhancement

#1242 Fix dead links in the markup reference page
  doc/rdoc/markup_reference.rb
Labels: documentation

#1236 Fix iPad Pro navigation not shown
  lib/rdoc/generator/template/darkfish/js/darkfish.js
Labels: bug

#1237 Hide hamburger on desktop
  lib/rdoc/generator/template/darkfish/css/rdoc.css
Labels: bug

#1244 Add attribute :force to RDoc::RubygemsHook just like RDoc::RubyGemsHook
  lib/rdoc/rubygems_hook.rb
  test/rdoc/test_rdoc_rubygems_hook.rb
Labels: bug

#1241 Print warnings for rdoc-ref links that can't be resolved
  .rdoc_options
  lib/rdoc/markup/to_html_crossref.rb
  lib/rdoc/options.rb
  test/rdoc/test_rdoc_markup_to_html_crossref.rb
  test/rdoc/test_rdoc_options.rb
Labels: enhancement

#1247 `aligns` may include `:center`
  lib/rdoc/markup/to_rdoc.rb
Labels: bug

#1240 Enable cross reference in code
  lib/rdoc/markup/formatter.rb
  lib/rdoc/markup/to_html_crossref.rb
  test/rdoc/test_rdoc_markup_to_html_crossref.rb
Labels: enhancement

#1238 Auto-hide navigation on link click
  lib/rdoc/generator/template/darkfish/js/darkfish.js
Labels: enhancement

#1251 Introduce `apply_default_exclude` config to separate default and user excluding patterns
  lib/rdoc/options.rb
  test/rdoc/test_rdoc_options.rb
Labels: bug

#1263 Documentation for #1240
  doc/rdoc/markup_reference.rb
Labels: documentation

#1259 Add autolink_excluded_words option to ignore cross-references
  lib/rdoc/markup/to_html_crossref.rb
  lib/rdoc/options.rb
  test/rdoc/test_rdoc_markup_to_html_crossref.rb
  test/rdoc/test_rdoc_options.rb
Labels: enhancement
