Repository ruby/rdoc, pull requests merged in 2025-03, with the labels that each got.

#1314 Fix CodeObject's inheritance tree document
  lib/rdoc/code_object.rb
Labels: documentation

#1317 Call` update_extend`s in `ClassModule#complete`
  lib/rdoc/code_object/class_module.rb
  test/rdoc/test_rdoc_class_module.rb
Labels: bug

#1320 Image alt tag header formatting
  lib/rdoc/markdown.kpeg
  lib/rdoc/markup/heading.rb
  lib/rdoc/markup/to_html.rb
  test/rdoc/test_rdoc_markdown.rb
  test/rdoc/test_rdoc_markup_heading.rb
Labels: bug, enhancement

#1330 Allow customizing path prefix through options
  lib/rdoc/code_object/class_module.rb
  lib/rdoc/code_object/top_level.rb
  lib/rdoc/options.rb
  test/rdoc/test_rdoc_class_module.rb
  test/rdoc/test_rdoc_options.rb
  test/rdoc/test_rdoc_top_level.rb
Labels: bug, enhancement
