Repository ruby/rdoc, pull requests merged in 2025-01, with the labels that each got.

#1271 [DOC] Remove unnecessary rdoc-ref missing example
  doc/rdoc/markup_reference.rb
Labels: documentation

#1270 Add missing `RDoc::RubygemsHook` API for `gem server`
  lib/rdoc/rubygems_hook.rb
Labels: bug

#1275 Enable `warn_missing_rdoc_ref` by default
  lib/rdoc/options.rb
  test/rdoc/test_rdoc_options.rb
Labels: enhancement

#1250 Display main page's Table of Contents when viewed from the index page
  lib/rdoc/generator/darkfish.rb
  lib/rdoc/generator/template/darkfish/index.rhtml
  test/rdoc/test_rdoc_generator_darkfish.rb
Labels: enhancement

#1210 Stop accepting `Document` objects as `CodeObject#comment`
  lib/rdoc/code_object.rb
  lib/rdoc/code_object/any_method.rb
  lib/rdoc/code_object/attr.rb
  lib/rdoc/code_object/class_module.rb
  lib/rdoc/code_object/constant.rb
  lib/rdoc/code_object/context/section.rb
  lib/rdoc/code_object/top_level.rb
  lib/rdoc/comment.rb
  lib/rdoc/generator/darkfish.rb
  lib/rdoc/parser/changelog.rb
  lib/rdoc/ri/driver.rb
  test/rdoc/test_rdoc_any_method.rb
  test/rdoc/test_rdoc_attr.rb
  test/rdoc/test_rdoc_class_module.rb
  test/rdoc/test_rdoc_code_object.rb
  test/rdoc/test_rdoc_comment.rb
  test/rdoc/test_rdoc_constant.rb
  test/rdoc/test_rdoc_context_section.rb
  test/rdoc/test_rdoc_generator_darkfish.rb
  test/rdoc/test_rdoc_parser_changelog.rb
  test/rdoc/test_rdoc_ri_driver.rb
  test/rdoc/test_rdoc_store.rb
  test/rdoc/test_rdoc_top_level.rb
Labels: bug
